# Description: Liten AI Configuration file
# Author: Liten AI
# Date: 2022-02-22
# Version: 0.0.1

# Customer can change settings as per their requirements. All setting names starting with _
# are reserved for internal use, and are not to be exposed to the user.
openai:
  # OpenAI API key to for API calls
  api_key: "<use OpenAI key here>"
spark:
  # Spark connect mode - local or remote
  connect_mode : "local" # "remote"  # local or remote
  # Spark local IP where  master is running, do local[n] for n threaded master
  # Spark remote URL where master is running is like sc://localhost:15002 for spark-connect-server
  connect_url : "local[*]" #"sc://localhost:15002"
liten:
  # Liten Datalake URL - assumes litenlakehouse.py is here for file scheme
  lakehouse_url: "/content/samplelogfiles/"
  # log file path
  _log_file: "/content/litenai.log"
